import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/commons/Header";
import Footer from "@/components/commons/Footer";
import { ToastContainer, Zoom, cssTransition } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NCT - Đến để tận hưởng nhu cầu thời trang của bạn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss={false}
          pauseOnHover={false}
          draggable
          transition={Zoom}
          closeButton={false}
          className='notification z-[999999] fixed top-0'
          toastClassName='notification-item'
          bodyClassName='notification-content'
        />
      </body>
    </html>
  );
}
